# Generated by Django 6.0 on 2025-12-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
