# Generated by Django 6.0 on 2025-12-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classsession_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
