# Generated by Django 6.0 on 2025-12-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classsession_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtype',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
