# Generated by Django 6.0 on 2026-02-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_classtype_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtype',
            name='is_group',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classtype',
            name='duration_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
