# Generated by Django 6.0 on 2026-02-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_classtype_group_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='total_sessions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
