# Generated by Django 6.0 on 2026-02-22 12:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_privateclassdetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateclassdetails',
            name='price_per_day',
        ),
        migrations.AddField(
            model_name='privateclassdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privateclassdetails',
            name='private_class_price_per_day',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='privateclassdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
