# Generated by Django 6.0 on 2026-02-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_seed_privateclassdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateclassdetails',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='privateclassdetails',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
