# Generated by Django 6.0 on 2026-02-22 12:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_remove_privateclassdetails_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateclass',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privateclass',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
