# Generated by Django 6.0 on 2026-02-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_privateclass_end_time_privateclass_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateclass',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
