# Generated by Django 6.0 on 2026-02-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_privateclass_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classbooking',
            name='is_active',
        ),
        migrations.AddField(
            model_name='classbooking',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
