# Generated by Django 6.0 on 2026-02-24 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0013_remove_classbooking_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='classsession',
            old_name='user',
            new_name='trainer',
        ),
        migrations.AddField(
            model_name='classsession',
            name='substitute_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituted_class_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privateclass',
            name='substitute_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituted_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PrivateClassAttendance',
        ),
    ]
