# Generated by Django 6.0 on 2026-03-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0016_move_completioncertificate_to_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classbooking',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='privateclass',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='privateclassdetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
