# Generated by Django 6.0 on 2026-04-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0017_alter_classbooking_id_alter_classsession_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classbooking',
            name='expiry_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privateclass',
            name='expiry_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
