# Generated by Django 6.0 on 2026-03-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='digital_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
