# Generated by Django 6.0 on 2026-03-16 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0015_completioncertificate'),
        ('reviews', '0002_review_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='certificate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='classes.completioncertificate'),
        ),
    ]
