# Generated by Django 6.0 on 2026-03-27 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_rename_completioncertificate_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='completioncertificate',
            table=None,
        ),
    ]
