# Generated by Django 6.0 on 2025-12-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
