# Generated by Django 6.0 on 2026-01-09 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0002_pool_is_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolQuality',
            fields=[
                ('quality_id', models.AutoField(primary_key=True, serialize=False)),
                ('cleanliness_rating', models.IntegerField()),
                ('pH_level', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('water_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chlorine_level', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualities', to='pool.pool')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('pool', 'date')},
            },
        ),
    ]
