# Generated by Django 6.0 on 2026-01-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_poolquality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='coordinates',
            field=models.CharField(max_length=100),
        ),
    ]
