# Generated by Django 6.0 on 2026-02-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0005_trainerpoolassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerpoolassignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
