# Generated by Django 5.1.3 on 2026-02-25 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0006_trainerpoolassignment_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='pool_images/')),
                ('caption', models.CharField(blank=True, max_length=120, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pool.pool')),
            ],
            options={
                'ordering': ['sort_order', 'image_id'],
            },
        ),
    ]
