# Generated by Django 6.0 on 2026-04-04 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0007_poolimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='image_url',
        ),
    ]
