# Generated by Django 5.1.3 on 2026-02-25

from django.db import migrations, models


def map_weekend_to_class_cancelled(apps, schema_editor):
    PrivateClassAttendance = apps.get_model('attendance', 'PrivateClassAttendance')
    PrivateClassAttendance.objects.filter(status='weekend').update(status='class_cancelled')


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(map_weekend_to_class_cancelled, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='privateclassattendance',
            name='status',
            field=models.CharField(
                choices=[
                    ('present', 'Student Present'),
                    ('absent', 'Student Absent'),
                    ('class_cancelled', 'Class Cancelled'),
                ],
                default='present',
                max_length=20,
            ),
        ),
    ]
